services:
  frontend:
    build:
      target: prod
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      target: prod
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - CORS_ORIGIN=http://localhost:80
